spring:
  profiles:
    active:
    - dev


---



spring:
  profiles: dev
  application:
    name: microservicecloud-config-wan-dev


---


spring:
  profiles: test
  application:
    name: microservicecloud-config-wan-test


---

spring:
  profiles: dev1   # 开发环境
  application:
    name: microservicecloud-config-dev

---

spring:
  profiles: test1   # 测试环境
  application:
    name: microservicecloud-config-test



